package com.saoke.joyreader.ui.home

import androidx.lifecycle.ViewModel
import com.saoke.joyreader.logic.model.BlogModel
import java.time.LocalDateTime

class HomeViewModel : ViewModel() {

    // TODO 测试数据
    private val _blogList: List<BlogModel> = listOf(
        BlogModel(
            "1",
            "0",
            "admin",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
        BlogModel(
            "1",
            "0",
            "骚客",
            "",
            "这是标题",
            "这是描述",
            "这是内容",
            LocalDateTime.of(2024, 3, 24, 14, 48, 22),
            0,
            0,
        ),
    )

    private val _tabs: List<String> = listOf("热门", "最新")
    val tabs: List<String> = _tabs

    private val _hotBlogList: List<BlogModel> = _blogList
    val hotBlogList: List<BlogModel> = _hotBlogList

    private val _latestBlogList: List<BlogModel> = _blogList
    val latestBlogList: List<BlogModel> = _latestBlogList
}